import './globals.css'
import { Inter } from 'next/font/google'
import NavBar from './components/NavBar';
import BackgroundGradients from './components/BackgroundGradients'
import MobileBackgroundGradients from './components/mobileBackgroundGradients';
import About from './pages/About';
import Home from './pages/Home';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="headerApp">
          <NavBar />
        </header>
        
        <div className="bgAnimationApp hidden md:block">
          <BackgroundGradients />
        </div>

        <div className="bgAnimationApp block md:hidden">
          <MobileBackgroundGradients />
        </div>

        <div className="bodyApp">
          {children}
        </div>
      </body>
    </html>
  )
}
